// ═══════════════════════════════════════════════════════════════
// AUDIO.JS — Spatial audio & ambient soundscape (Web Audio API)
// ═══════════════════════════════════════════════════════════════
'use strict';

window.AUDIO = (function(){
  let ctx = null, masterGain = null, started = false;

    // ── INIT ────────────────────────────────────────────────────
      function init(){
          if(started) return;
              try{
                    ctx = new (window.AudioContext || window.webkitAudioContext)();
                          masterGain = ctx.createGain();
                                masterGain.gain.value = 0.3;
                                      masterGain.connect(ctx.destination);
                                            started = true;
                                                } catch(e){ console.warn('Audio unavailable:', e); }
                                                  }

                                                    function resume(){ if(ctx && ctx.state==='suspended') ctx.resume(); }

                                                      // ── OSCILLATOR UTILITY ───────────────────────────────────────
                                                        function osc(freq, type='sine', gain=0.1, dur=null){
                                                            if(!ctx) return null;
                                                                const o = ctx.createOscillator();
                                                                    const g = ctx.createGain();
                                                                        o.type = type;
                                                                            o.frequency.value = freq;
                                                                                g.gain.value = gain;
                                                                                    o.connect(g); g.connect(masterGain);
                                                                                        o.start();
                                                                                            if(dur) { g.gain.linearRampToValueAtTime(0, ctx.currentTime+dur); o.stop(ctx.currentTime+dur); }
                                                                                                return {osc:o, gain:g};
                                                                                                  }

                                                                                                    // ── NOISE GENERATOR ──────────────────────────────────────────
                                                                                                      function whiteNoise(gain=0.05){
                                                                                                          if(!ctx) return null;
                                                                                                              const bufSize=2*ctx.sampleRate, buf=ctx.createBuffer(1,bufSize,ctx.sampleRate);
                                                                                                                  const data=buf.getChannelData(0);
                                                                                                                      for(let i=0;i<bufSize;i++) data[i]=Math.random()*2-1;
                                                                                                                          const src=ctx.createBufferSource(); src.buffer=buf; src.loop=true;
                                                                                                                              const g=ctx.createGain(); g.gain.value=gain;
                                                                                                                                  const bpf=ctx.createBiquadFilter(); bpf.type='bandpass';
                                                                                                                                      src.connect(bpf); bpf.connect(g); g.connect(masterGain);
                                                                                                                                          src.start();
                                                                                                                                              return {source:src, gain:g, filter:bpf};
                                                                                                                                                }

                                                                                                                                                  // ── AMBIENT LAYERS ───────────────────────────────────────────
                                                                                                                                                    let ambients = {};

                                                                                                                                                      function makeSpaceAmbient(){
                                                                                                                                                          if(!ctx) return;
                                                                                                                                                              // Deep space drone — very low frequency
                                                                                                                                                                  const drone1 = osc(32, 'sine', 0.06);
                                                                                                                                                                      const drone2 = osc(48, 'sine', 0.04);
                                                                                                                                                                          const drone3 = osc(64, 'triangle', 0.03);

                                                                                                                                                                              // Slow LFO modulation
                                                                                                                                                                                  const lfo = ctx.createOscillator();
                                                                                                                                                                                      const lfoGain = ctx.createGain();
                                                                                                                                                                                          lfo.frequency.value = 0.08;
                                                                                                                                                                                              lfoGain.gain.value = 8;
                                                                                                                                                                                                  lfo.connect(lfoGain);
                                                                                                                                                                                                      if(drone1) lfoGain.connect(drone1.osc.frequency);
                                                                                                                                                                                                          lfo.start();

                                                                                                                                                                                                              // Cosmic noise (very quiet)
                                                                                                                                                                                                                  const noise = whiteNoise(0.008);
                                                                                                                                                                                                                      if(noise){
                                                                                                                                                                                                                            noise.filter.frequency.value = 200;
                                                                                                                                                                                                                                  noise.filter.Q.value = 0.5;
                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                          ambients.space = {drone1, drone2, drone3, lfo, noise};
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                              function makeSunAmbient(){
                                                                                                                                                                                                                                                  if(!ctx) return;
                                                                                                                                                                                                                                                      // Solar wind hiss
                                                                                                                                                                                                                                                          const hiss = whiteNoise(0.04);
                                                                                                                                                                                                                                                              if(hiss){ hiss.filter.frequency.value = 800; hiss.filter.Q.value = 0.3; }
                                                                                                                                                                                                                                                                  // Solar rumble
                                                                                                                                                                                                                                                                      const rumble = osc(28, 'sawtooth', 0.05);
                                                                                                                                                                                                                                                                          const rumble2 = osc(44, 'sine', 0.03);
                                                                                                                                                                                                                                                                              ambients.sun = {hiss, rumble, rumble2};
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                  // ── SOUND EVENTS ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                    function playZoom(direction){
                                                                                                                                                                                                                                                                                        // direction: 1 = zoom in, -1 = zoom out
                                                                                                                                                                                                                                                                                            if(!ctx) return;
                                                                                                                                                                                                                                                                                                const freq = direction > 0 ? 220 : 110;
                                                                                                                                                                                                                                                                                                    const o = ctx.createOscillator();
                                                                                                                                                                                                                                                                                                        const g = ctx.createGain();
                                                                                                                                                                                                                                                                                                            const filter = ctx.createBiquadFilter();
                                                                                                                                                                                                                                                                                                                o.type = 'sine';
                                                                                                                                                                                                                                                                                                                    o.frequency.setValueAtTime(freq, ctx.currentTime);
                                                                                                                                                                                                                                                                                                                        o.frequency.exponentialRampToValueAtTime(freq*(direction>0?2:0.5), ctx.currentTime+0.3);
                                                                                                                                                                                                                                                                                                                            g.gain.setValueAtTime(0, ctx.currentTime);
                                                                                                                                                                                                                                                                                                                                g.gain.linearRampToValueAtTime(0.08, ctx.currentTime+0.05);
                                                                                                                                                                                                                                                                                                                                    g.gain.linearRampToValueAtTime(0, ctx.currentTime+0.4);
                                                                                                                                                                                                                                                                                                                                        filter.type = 'lowpass'; filter.frequency.value = 1000;
                                                                                                                                                                                                                                                                                                                                            o.connect(filter); filter.connect(g); g.connect(masterGain);
                                                                                                                                                                                                                                                                                                                                                o.start(); o.stop(ctx.currentTime+0.5);
                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                    function playNavClick(){
                                                                                                                                                                                                                                                                                                                                                        if(!ctx) return;
                                                                                                                                                                                                                                                                                                                                                            const o=ctx.createOscillator(), g=ctx.createGain();
                                                                                                                                                                                                                                                                                                                                                                o.type='triangle'; o.frequency.value=880;
                                                                                                                                                                                                                                                                                                                                                                    o.frequency.exponentialRampToValueAtTime(440,ctx.currentTime+0.15);
                                                                                                                                                                                                                                                                                                                                                                        g.gain.setValueAtTime(0.1,ctx.currentTime);
                                                                                                                                                                                                                                                                                                                                                                            g.gain.linearRampToValueAtTime(0,ctx.currentTime+0.2);
                                                                                                                                                                                                                                                                                                                                                                                o.connect(g); g.connect(masterGain);
                                                                                                                                                                                                                                                                                                                                                                                    o.start(); o.stop(ctx.currentTime+0.25);
                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                        function playScaleTransition(){
                                                                                                                                                                                                                                                                                                                                                                                            // Ethereal sound when crossing scale boundaries
                                                                                                                                                                                                                                                                                                                                                                                                if(!ctx) return;
                                                                                                                                                                                                                                                                                                                                                                                                    const freqs=[220,330,440,550];
                                                                                                                                                                                                                                                                                                                                                                                                        freqs.forEach((f,i)=>{
                                                                                                                                                                                                                                                                                                                                                                                                              const o=ctx.createOscillator(), g=ctx.createGain();
                                                                                                                                                                                                                                                                                                                                                                                                                    o.type='sine'; o.frequency.value=f;
                                                                                                                                                                                                                                                                                                                                                                                                                          g.gain.setValueAtTime(0,ctx.currentTime+i*0.12);
                                                                                                                                                                                                                                                                                                                                                                                                                                g.gain.linearRampToValueAtTime(0.06,ctx.currentTime+i*0.12+0.1);
                                                                                                                                                                                                                                                                                                                                                                                                                                      g.gain.linearRampToValueAtTime(0,ctx.currentTime+i*0.12+0.8);
                                                                                                                                                                                                                                                                                                                                                                                                                                            o.connect(g); g.connect(masterGain);
                                                                                                                                                                                                                                                                                                                                                                                                                                                  o.start(ctx.currentTime+i*0.12);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        o.stop(ctx.currentTime+i*0.12+0.9);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ── SCALE-BASED MUSIC ────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Generative ambient based on current zoom level
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let musicInterval = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      let lastScale = '';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function updateMusic(scaleName){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(!ctx || scaleName === lastScale) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                lastScale = scaleName;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    playScaleTransition();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ── VOLUME CONTROL ───────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          function setVolume(v){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if(masterGain) masterGain.gain.setTargetAtTime(v*0.4, ctx.currentTime, 0.1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function toggleMute(){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if(!masterGain) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const cur = masterGain.gain.value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              masterGain.gain.setTargetAtTime(cur>0.01?0:0.3, ctx.currentTime, 0.1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return cur > 0.01; // returns true if now muted
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // ── START ────────────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function start(){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            init();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(!ctx) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    makeSpaceAmbient();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        makeSunAmbient();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return { start, resume, setVolume, toggleMute, playZoom, playNavClick, playScaleTransition, updateMusic };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            