// ═══════════════════════════════════════════════════════════════
// PLANETS.JS — Full solar system with Keplerian physics
// ═══════════════════════════════════════════════════════════════
'use strict';

window.PLANETS_DATA = [
  {
      id:'mercury', name:'Mercure', emoji:'☿',
          au:0.387, km:2439.7, period:87.97, rotPeriod:58.646, tilt:0.034, rotDir:1,
              orbitSpeed:47.87, eqSpeed:10.83, moons:0,
                  color:'#b5a090', emis:'#2a1a10',
                      atmos:null,
                          info:`Distance: 0.387 UA\nDiamètre: 4 879 km\nPériode orbitale: 87.97 jours\nInclinaison axiale: 0.034°\nRotation: 58.65 jours\nVitesse orbitale: 47.9 km/s\nVitesse rotation: 10.8 km/h\nLunes: 0\nAtmosphère: Quasi absente\nTempérature: −180°C / +430°C`,
                              moons_list:[]
                                },
                                  {
                                      id:'venus', name:'Vénus', emoji:'♀',
                                          au:0.723, km:6051.8, period:224.7, rotPeriod:243.02, tilt:177.4, rotDir:-1,
                                              orbitSpeed:35.02, eqSpeed:6.52, moons:0,
                                                  color:'#e8c87a', emis:'#402800',
                                                      atmos:'#ffcc44', atmosIntensity:1.8, atmosFalloff:2.8,
                                                          info:`Distance: 0.723 UA\nDiamètre: 12 104 km\nPériode orbitale: 224.7 jours\nInclinaison axiale: 177.4° ← rétrograde\nRotation: 243.0 jours (inversée)\nVitesse orbitale: 35.0 km/s\nVitesse rotation: 6.5 km/h\nLunes: 0\nAtmosphère: CO₂ 96%, N₂ 3.5%\nPression: 92 bars\nTempérature: +465°C (effet serre)`,
                                                              moons_list:[]
                                                                },
                                                                  {
                                                                      id:'earth', name:'Terre', emoji:'♁',
                                                                          au:1.000, km:6371.0, period:365.25, rotPeriod:0.9973, tilt:23.44, rotDir:1,
                                                                              orbitSpeed:29.78, eqSpeed:1674.4, moons:1,
                                                                                  color:'#4488cc', emis:'#001840',
                                                                                      atmos:'#3366ff', atmosIntensity:1.3, atmosFalloff:3.2,
                                                                                          clouds:true,
                                                                                              info:`Distance: 1.000 UA\nDiamètre: 12 742 km\nPériode orbitale: 365.25 jours\nInclinaison axiale: 23.44°\nRotation: 23h 56min\nVitesse orbitale: 29.8 km/s\nVitesse rotation: 1 674 km/h\nLunes: 1 (La Lune)\nAtmosphère: N₂ 78%, O₂ 21%\nPression: 1 bar\nTempérature: −88°C / +58°C`,
                                                                                                  moons_list:[
                                                                                                        { name:'Lune', km:1737, dist:0.6, period:27.32, color:'#c8c0b0', tilt:5.14, info:'Satellite naturel de la Terre\nDiamètre: 3 474 km\nDist. Terre: 384 400 km\nPériode: 27.3 jours\nPas d\'atmosphère' }
                                                                                                            ]
                                                                                                              },
                                                                                                                {
                                                                                                                    id:'mars', name:'Mars', emoji:'♂',
                                                                                                                        au:1.524, km:3389.5, period:686.97, rotPeriod:1.026, tilt:25.19, rotDir:1,
                                                                                                                            orbitSpeed:24.07, eqSpeed:868.2, moons:2,
                                                                                                                                color:'#c04410', emis:'#300800',
                                                                                                                                    atmos:'#ff6622', atmosIntensity:0.6, atmosFalloff:4.0,
                                                                                                                                        info:`Distance: 1.524 UA\nDiamètre: 6 779 km\nPériode orbitale: 686.97 jours\nInclinaison axiale: 25.19°\nRotation: 24h 37min\nVitesse orbitale: 24.1 km/s\nVitesse rotation: 868 km/h\nLunes: 2 (Phobos, Deimos)\nAtmosphère: CO₂ 95%, N₂ 2.6%\nPression: 0.006 bar\nTempérature: −153°C / +20°C`,
                                                                                                                                            moons_list:[
                                                                                                                                                  { name:'Phobos', km:11.3, dist:0.3, period:0.3189, color:'#907060', tilt:1.1, info:'Lune de Mars\nDiamètre: 22.5 km (irrégulier)\nOrbit: 9 376 km\nPériode: 7h 39min\nSe rapproche de Mars (spirale)' },
                                                                                                                                                        { name:'Deimos', km:6.2,  dist:0.55,period:1.2624, color:'#807060', tilt:1.8, info:'Petite lune de Mars\nDiamètre: 12.4 km (irrégulier)\nOrbit: 23 463 km\nPériode: 30.3 heures' }
                                                                                                                                                            ]
                                                                                                                                                              },
                                                                                                                                                                {
                                                                                                                                                                    id:'jupiter', name:'Jupiter', emoji:'♃',
                                                                                                                                                                        au:5.203, km:71492, period:4332.59, rotPeriod:0.4135, tilt:3.13, rotDir:1,
                                                                                                                                                                            orbitSpeed:13.07, eqSpeed:45300, moons:95,
                                                                                                                                                                                color:'#c8883a', emis:'#301800',
                                                                                                                                                                                    atmos:'#c07030', atmosIntensity:1.0, atmosFalloff:2.5,
                                                                                                                                                                                        info:`Distance: 5.203 UA\nDiamètre: 142 984 km\nPériode orbitale: 11.86 ans\nInclinaison axiale: 3.13°\nRotation: 9h 55min (la + rapide)\nVitesse orbitale: 13.1 km/s\nVitesse rotation: 45 300 km/h\nLunes: 95 (dont 4 galiléennes)\nAtmosphère: H₂ 89%, He 10%\nGrande Tache Rouge: tempête >300 ans`,
                                                                                                                                                                                            moons_list:[
                                                                                                                                                                                                  { name:'Io',       km:1821.6, dist:1.6, period:1.769,  color:'#d8b820', tilt:0,   info:'Lune la + volcanique du SS\nDiamètre: 3 643 km\nOrbit: 421 700 km\n400+ volcans actifs\nRésonnance orbitale 1:2:4' },
                                                                                                                                                                                                        { name:'Europe',   km:1560.8, dist:2.3, period:3.551,  color:'#c0a878', tilt:0.47,info:'Océan global sous la glace\nDiamètre: 3 122 km\nOrbit: 671 100 km\nPotentiellement habitable' },
                                                                                                                                                                                                              { name:'Ganymède', km:2634.1, dist:3.4, period:7.155,  color:'#a09080', tilt:0.2, info:'Plus grande lune du SS\nDiamètre: 5 268 km (> Mercure)\nOrbit: 1 070 400 km\nChamp magnétique propre' },
                                                                                                                                                                                                                    { name:'Callisto',km:2410.3, dist:5.0, period:16.69,  color:'#706050', tilt:0.19,info:'Surface la + cratérisée du SS\nDiamètre: 4 820 km\nOrbit: 1 882 700 km\nPossible océan subsurface' }
                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                          },
                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                id:'saturn', name:'Saturne', emoji:'♄',
                                                                                                                                                                                                                                    au:9.537, km:60268, period:10759.2, rotPeriod:0.4440, tilt:26.73, rotDir:1,
                                                                                                                                                                                                                                        orbitSpeed:9.68, eqSpeed:35500, moons:146,
                                                                                                                                                                                                                                            color:'#e8d090', emis:'#302010',
                                                                                                                                                                                                                                                atmos:'#e8d080', atmosIntensity:0.9, atmosFalloff:2.8,
                                                                                                                                                                                                                                                    rings:true,
                                                                                                                                                                                                                                                        info:`Distance: 9.537 UA\nDiamètre: 120 536 km\nPériode orbitale: 29.46 ans\nInclinaison axiale: 26.73°\nRotation: 10h 42min\nVitesse orbitale: 9.7 km/s\nVitesse rotation: 35 500 km/h\nLunes: 146 confirmées\nAnneaux: 7 groupes, 280 000 km Ø\nAtmosphère: H₂ 96%, He 3%\nDensité: 0.69 (flotte sur l'eau!)`,
                                                                                                                                                                                                                                                            moons_list:[
                                                                                                                                                                                                                                                                  { name:'Titan',  km:2574.7, dist:2.5, period:15.945, color:'#c89030', tilt:0.35, info:'2ème plus grande lune du SS\nDiamètre: 5 149 km\nAtmosphère dense d\'azote\nLacs de méthane liquide\nPossible vie pré-biotique' },
                                                                                                                                                                                                                                                                        { name:'Rhéa',   km:764.3,  dist:1.8, period:4.518,  color:'#b8a898', tilt:0.35, info:'Lune: Rhéa\nDiamètre: 1 529 km\nOrbit: 527 000 km\nSurface cratérisée, glacée' },
                                                                                                                                                                                                                                                                              { name:'Dioné',  km:561.7,  dist:1.4, period:2.737,  color:'#c0b8a8', tilt:0.02, info:'Lune: Dioné\nDiamètre: 1 123 km\nFalaises de glace géantes' },
                                                                                                                                                                                                                                                                                    { name:'Téthys', km:533.0,  dist:1.1, period:1.888,  color:'#d0c8c0', tilt:1.12, info:'Lune: Téthys\nDiamètre: 1 066 km\nCrater Odyssée: 450 km Ø' }
                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                id:'uranus', name:'Uranus', emoji:'⛢',
                                                                                                                                                                                                                                                                                                    au:19.19, km:25559, period:30688.5, rotPeriod:0.7183, tilt:97.77, rotDir:-1,
                                                                                                                                                                                                                                                                                                        orbitSpeed:6.80, eqSpeed:9320, moons:28,
                                                                                                                                                                                                                                                                                                            color:'#70d8d8', emis:'#002828',
                                                                                                                                                                                                                                                                                                                atmos:'#40d8d8', atmosIntensity:0.8, atmosFalloff:3.0,
                                                                                                                                                                                                                                                                                                                    rings:true, thinRings:true,
                                                                                                                                                                                                                                                                                                                        info:`Distance: 19.19 UA\nDiamètre: 51 118 km\nPériode orbitale: 84.01 ans\nInclinaison axiale: 97.77° ← axe couché!\nRotation: 17h 14min (rétrograde)\nVitesse orbitale: 6.8 km/s\nVitesse rotation: 9 320 km/h\nLunes: 28 (nommées d'après Shakespeare)\nAnneaux: 13 fins anneaux sombres\nAtmosphère: H₂ 83%, He 15%, CH₄ 2.3%`,
                                                                                                                                                                                                                                                                                                                            moons_list:[
                                                                                                                                                                                                                                                                                                                                  { name:'Titania', km:788.9, dist:1.4, period:8.706,  color:'#b8b0c0', tilt:97.8, info:'Plus grande lune d\'Uranus\nDiamètre: 1 578 km\nCanyons et cratères' },
                                                                                                                                                                                                                                                                                                                                        { name:'Obéron',  km:761.4, dist:1.9, period:13.463, color:'#a0a0b0', tilt:97.8, info:'2ème plus grande lune d\'Uranus\nDiamètre: 1 523 km' },
                                                                                                                                                                                                                                                                                                                                              { name:'Umbriel', km:584.7, dist:1.0, period:4.144,  color:'#706880', tilt:97.8, info:'Surface très sombre\nDiamètre: 1 169 km' },
                                                                                                                                                                                                                                                                                                                                                    { name:'Ariel',   km:578.9, dist:.75, period:2.520,  color:'#c0b8d0', tilt:97.8, info:'Surface la plus brillante\nDiamètre: 1 158 km' }
                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                id:'neptune', name:'Neptune', emoji:'♆',
                                                                                                                                                                                                                                                                                                                                                                    au:30.07, km:24764, period:60182, rotPeriod:0.6713, tilt:28.32, rotDir:1,
                                                                                                                                                                                                                                                                                                                                                                        orbitSpeed:5.43, eqSpeed:9720, moons:16,
                                                                                                                                                                                                                                                                                                                                                                            color:'#3060e8', emis:'#001030',
                                                                                                                                                                                                                                                                                                                                                                                atmos:'#2040e8', atmosIntensity:1.1, atmosFalloff:3.0,
                                                                                                                                                                                                                                                                                                                                                                                    info:`Distance: 30.07 UA\nDiamètre: 49 528 km\nPériode orbitale: 164.8 ans\nInclinaison axiale: 28.32°\nRotation: 16h 6min\nVitesse orbitale: 5.4 km/s\nVitesse rotation: 9 720 km/h\nLunes: 16 (Triton rétrograde)\nAtmosphère: H₂ 80%, He 19%, CH₄ 1.5%\nVents: jusqu'à 2 100 km/h!`,
                                                                                                                                                                                                                                                                                                                                                                                        moons_list:[
                                                                                                                                                                                                                                                                                                                                                                                              { name:'Triton', km:1353.4, dist:1.2, period:-5.877, color:'#b0c8d8', tilt:157, info:'Plus grande lune de Neptune\nDiamètre: 2 707 km\nOrbit RÉTROGRADE (capturée)\nGeysers d\'azote actifs\nDestinée à se désintégrer (~3.6 Gans)' }
                                                                                                                                                                                                                                                                                                                                                                                                  ]
                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                    ];

                                                                                                                                                                                                                                                                                                                                                                                                    // ── KEPLERIAN ORBIT SOLVER ───────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                    window.Kepler = {
                                                                                                                                                                                                                                                                                                                                                                                                      // Solve Kepler equation E - e·sin(E) = M using Newton-Raphson
                                                                                                                                                                                                                                                                                                                                                                                                        solveKepler(M, e, tol=1e-8, maxIter=50){
                                                                                                                                                                                                                                                                                                                                                                                                            let E = e < 0.8 ? M : Math.PI;
                                                                                                                                                                                                                                                                                                                                                                                                                for(let i=0; i<maxIter; i++){
                                                                                                                                                                                                                                                                                                                                                                                                                      const dE = (E - e*Math.sin(E) - M) / (1 - e*Math.cos(E));
                                                                                                                                                                                                                                                                                                                                                                                                                            E -= dE;
                                                                                                                                                                                                                                                                                                                                                                                                                                  if(Math.abs(dE) < tol) break;
                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                          return E;
                                                                                                                                                                                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                                                                                                                                                                              // True anomaly from eccentric anomaly
                                                                                                                                                                                                                                                                                                                                                                                                                                                trueAnomaly(E, e){
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 2 * Math.atan2(
                                                                                                                                                                                                                                                                                                                                                                                                                                                          Math.sqrt(1+e) * Math.sin(E/2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                Math.sqrt(1-e) * Math.cos(E/2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Position in orbital plane
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          orbitPos(a, e, inc, omega, node, M){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const E  = this.solveKepler(M, e);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const nu = this.trueAnomaly(E, e);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const r  = a * (1 - e*Math.cos(E));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const xo = r * Math.cos(nu);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const yo = r * Math.sin(nu);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Rotate to 3D
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const cO=Math.cos(node), sO=Math.sin(node);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const cI=Math.cos(inc),  sI=Math.sin(inc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const cW=Math.cos(omega),sW=Math.sin(omega);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return new THREE.Vector3(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        (cO*cW - sO*sW*cI)*xo + (-cO*sW - sO*cW*cI)*yo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (sI*sW)*xo + (sI*cW)*yo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    (sO*cW + cO*sW*cI)*xo + (-sO*sW + cO*cW*cI)*yo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          